name: snake
channels:
  - conda-forge
  - base
  - bioconda
  - R
  - defaults
dependencies:
  - snakemake
  - r-base=4.1.3
  - r-tidyverse=1.3.2
  - wget=1.20.3
  - snakemake==7.32.4
  - perl
  - pandas
  - flask  # Adicione esta linha